### ISSUE TITLE
Jump to line in PDF from editor

### ISSUE THREAD

**Issue by tlinnet** [overleaf/web#121]
Hi.

I would like the possibility to jump from the line in the editor to the line in the pdf.
This should be possible with synctex.

This is also explained here:
http://tex.stackexchange.com/questions/161579/jump-between-pdf-and-source-file-using-a-document-split-into-master-and-child

http://tex.stackexchange.com/questions/127815/texmaker-forward-backward-search

In Texmaker, this is the command for Pdflatex
pdflatex -synctex=1 -interaction=nonstopmode %.tex

and for latex is:
latex -interaction=nonstopmode %.tex

**Comment by marnunez** [comment]
Is there a hotkey for forward synctex for Overleaf v2?
