### ISSUE TITLE
Allow end user to clear compile directory/cache/aux files

### ISSUE THREAD

**Issue by jpallen** [overleaf/web#15]
It's possible for LaTeX to get stuck in a state where the aux files need clearing. This can done with a DELETE request to http://<clsi>/project/<project-id>, but is not hooked into the user interface yet. Adding a dropdown to the 'Recompile' button with this option is probably the best way, and have this call an HTTP end point which is proxied to the CLSI.

**Comment by thuyen** [comment]
There's a trash icon for clearing cache in the end of error/warning list.

**Comment by leoheck** [comment]
Is it possible to create a button to remove a folder? The action is remove all the projects from the tag and by the end remove the folder. And create a button to rename the folder.
