### ISSUE TITLE
Disable word-wrapping in editor

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [overleaf/web#223]
So, I often work on small laptop screens; and I also prefer my code (including LaTeX documents) hard-wrapped (at 100 columns, for whatever it's worth.)

This isn't playing too well with the ShareLaTeX editor: I was shocked to see vim-command support, and that's really exciting; so I have high hopes that perhaps I could convince you to offer a flag to disable Ace's soft-wrapping entirely?

**Comment by mgranvik** [comment]
I second this suggestion. Although it seems a small issue, the soft-wrapping makes me walk away from sharelatex.

**Comment by paolieri** [comment]
I second this suggestion as well. Hard-wrapping is very important if you synchronize to GitHub and want to be able to check `git diff` outputs. With soft-wrapping, it's very hard to check what changed in a line. Many collaborators lamented this. Also: I think it should be a project setting, not a user one.

**Comment by jpallen** [comment]
This isn't on our roadmap because we're always very cautious about adding more and more settings when the defaults work well for people, but I'll leave this open as an ongoing gauge of interest

**Comment by paolieri** [comment]
That is indeed a good policy!

But I think that this would be a very important feature. Merge and diff algorithms are line-oriented; if you put an entire paragraph on one line, you make those tasks much more difficult. Especially when collaborating with authors that use their own editor and git instead of the online one (the "track changes" feature in the online editor makes this easier).

I can help with the implementation if this feature is added to the roadmap. Meanwhile, a temporary solution is to use `git diff --word-diff`.

**Comment by mlaneuville** [comment]
I would also very much like that feature for the reasons above.

**Comment by moorepants** [comment]
I support hard wrapping. Soft wraps pretty much make navigation to specific locations very difficult. Hard wraps are needed for vim-mode.

**Comment by brianlarkins** [comment]
another vote for hard wrapping. cut/paste can be awful with vim-mode.

**Comment by glavrentiadis** [comment]
I would also support this feature for the reasons mentioned above

**Comment by quebin31** [comment]
Hard wrapping would be really cool, currently working with Vim mode is awful.

**Comment by heshameraqi** [comment]
Tables are completely missed up without this feature. Please add it.

**Comment by juanfung** [comment]
Agree 100% about disabling soft wrapping and supporting hard wrapping! Hard wrapping is especially important, for all the reasons already mentioned

**Comment by tomekjaworski** [comment]
Such editor line wrapping configuration would be very helpful.

**Comment by tooHotSpot** [comment]
Very important for laptops. I agree with above.

**Comment by chrisjsewell** [comment]
+1

**Comment by PatricioClark** [comment]
Yes, please :+1:

**Comment by sebhahn** [comment]
What is the current status on this feature?

**Comment by NilsEnevoldsen** [comment]
## Workaround

Use this bookmarklet:

`javascript:ace.edit($(".ace-editor-body")[0]).getSession().setUseWrapMode(false);`

**Comment by sebhahn** [comment]
@NilsEnevoldsen how to set e.g. 80 chars for hardwrap?

**Comment by NilsEnevoldsen** [comment]
@sebhahn Hard wrapping is not supported with the Ace editor (https://github.com/ajaxorg/ace/issues/2865). I don't know if character wrapping is supported.

You can set 80-character-width soft word wrap with this bookmarklet:

`javascript:ace.edit($(".ace-editor-body")[0]).getSession().setWrapLimitRange(80,80);`

**Comment by Kee-Wang** [comment]
> ## Workaround
> Use this bookmarklet:
> 
> `javascript:ace.edit($(".ace-editor-body")[0]).getSession().setUseWrapMode(false);`


This saves my day! Thanks! 
For those who has zero knowledge (such as I did) about booklet, here is the example about how to do it in Chrome:

1.  Create a new bookmark and fill the Name and URL as following:

2.  Name: _NoWrapInOverleaf_  (or what ever name suits you)

3. URL: `javascript:ace.edit($(".ace-editor-body")[0]).getSession().setUseWrapMode(false);` 

4. Save the bookmark. Now turn to your Overleaf page have the text editor. Click the bookmark you just saved. Now you should be able to see texts in the editor are no longer wrapped.

The URL basically tells the browser to execute the Javescript code which asks the online text editor ([Ace](https://ace.c9.io/)) to turn off wrap mode.

**Comment by Lorentz-Ipsum** [comment]
> This saved my day! Thanks!
> For those who has zero knowledge (such as I did) about booklet, here is the example about how to do it in Chrome:

This method also works on Firefox. 

It is such a useful feature I would love to see an option to enable/disable it on the Settings sidebar.

**Comment by aharwood2** [comment]
Bump -- this would be awesome.

**Comment by bluewww** [comment]
dito

**Comment by adamconkey** [comment]
I would benefit from hard wraps. I collaborate with someone using emacs (not in overleaf) and they hard wrap everything, so when I pull the changes in overleaf it's a mess.

**Comment by i-abr** [comment]
Agreed, hard wrap would make me want to use overleaf a lot more.

**Comment by mcamurri** [comment]
Sama here, please

**Comment by Jerry-Ma** [comment]
I have been using vim and hard wrapping for my tex editting, and just now I tried using overleaf the first time, and immediately identified this barrier.

I would have definitely turned to overleaf from now on if this feather were in place.

**Comment by berghaus** [comment]
Would be appreciated. Note the workaround posted by @NilsEnevoldsen and explained by @Kee-Wang above

**Comment by luiarthur** [comment]
Yes, would love hard wrapping as a vim user.

**Comment by ahmadryan** [comment]
> > ## Workaround
> > Use this bookmarklet:
> > `javascript:ace.edit($(".ace-editor-body")[0]).getSession().setUseWrapMode(false);`
> 
> This saved my day! Thanks!
> For those who has zero knowledge (such as I did) about booklet, here is the example about how to do it in Chrome:
> 
> 1. Create a new bookmark and fill the Name and URL as following:
> 2. Name: _NoWrapInOverleaf_  (or what ever name suits you)
> 3. URL: `javascript:ace.edit($(".ace-editor-body")[0]).getSession().setUseWrapMode(false);`
> 4. Save the bookmark. Now turn to your Overleaf page that has the text editor. Click the bookmark you just saved. Now you should be able to see texts in the editor are no longer wrapped.
> 
> The URL basically tells the browser to execute the Javescript code which asks the online text editor ([Ace](https://ace.c9.io/)) to turn off wrap mode. To turn the wrap mode back, simply refresh the page.

Kinda sad that the workaround doesn't work for Microsoft Edge. Any suggestion?

**Comment by dbogatov** [comment]
We always have an option to go to the javascript console (in Safari, for example, it's Develop -> Show JavaScript Console) and insert the script manually (copy-paste and hit Enter).

Don't copy-paste `javascript:` part.
`ace.edit($(".ace-editor-body")[0]).getSession().setUseWrapMode(false);`

**Comment by chrstfer** [comment]
The editor works very well overall on mobile (in both firefox beta for android and the Fennec firefox build for android), but unfortunately I don't know of any way to apply the workaround. It would really be nice to have this as a UI option.

Long-shot related suggestion: add emacs's "fill-paragraph" and "fill-region" as keybinds for emacs mode.

**Comment by FrogFlint** [comment]
If you want that bookmarklet to work as a toggle, you can use ```javascript:(()=>{let s=ace.edit($(".ace-editor-body")[0]).getSession();s.setUseWrapMode(!s.$useWrapMode)})()```

**Comment by tillahoffmann** [comment]
If you've got TamperMonkey installed, the following user script will add a button to toggle text wrapping to the toolbar.

```javascript
// ==UserScript==
// @name         Overleaf customisation.
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://www.overleaf.com/project/*
// @grant        none
// ==/UserScript==

(function() {
    'use strict';

    setTimeout(function () {
        var toolbar = document.querySelector('div.toolbar-editor > div.toolbar-right');
        var element = document.createElement('A');
        element.textContent = 'Toggle wrap';
        element.onclick = function() {
            var editor = document.querySelector('.ace-editor-body');
            let session = ace.edit(editor).getSession();
            session.setUseWrapMode(!session.$useWrapMode)
        };
        toolbar.insertBefore(element, toolbar.children[0]);
    }, 3000);
})();
```

**Comment by dbogatov** [comment]
@tillahoffmann , great (temporary) solution!

Hey, devs, apparently, it will take you the entire couple lines of JS code to make life easier for us!
How did you even imagine people working with large tables in web editor with wrapping?

**Comment by chrstfer** [comment]
@tillahoffmann would you be interested in integrating that into the official client and submitting a PR?

**Comment by tillahoffmann** [comment]
@chrstfer, I'm unfortunately not a competent web developer, but anyone who has the skills to integrate it into the codebase is welcome to use whatever is useful from [the snippet above](https://github.com/overleaf/web/issues/223#issuecomment-824362238).

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
