### ISSUE TITLE
Can't navigate in spell-check menu with keyboard

### ISSUE THREAD

**Issue by AuHau** [overleaf/web#414]
When you open spell-check menu, you can't navigate through it with keyboard's arrows (down/up) to choose the right correction. The browser's context menu (after the right click) is able to do that, so I think it is rather major inconsistency or even bug. 

This behavior (navigating with keyboard) is especially welcomed, when you use the context (menu) key on keyboard, while writing and correcting spelling errors as it is very easy and fast, since you don't have to put down your hands from the keyboard to reach the mouse.

**Comment by jpallen** [comment]
👍  PRs would be welcome for this.

**Comment by podschwadt** [comment]
It would also be great to open it using the keyboard. For example by pressing the menu key

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
