### ISSUE TITLE
Code check does not work for hyperref

### ISSUE THREAD

**Issue by Philipp91** [overleaf/web#460]
`\ref{a_b}` and `\vref{a_b}` work fine and the `a_b` part gets highlighted in green. So ShareLaTeX recognizes that it's a label and probably features like #9 would work with it once implemented.

`\cref{a_b}`, `\pageref{a_b}` and `\hyperref{a_b}` do not have the highlighting, but that's fine for me.

`\hyperref[a_b]{test}` marks the underscore with "_ must be inside math mode", but the command is just as valid as the ones before and compiles fine. The label can be in the optional argument, in this case the main argument becomes regular text.

Here's what I found so far:
https://github.com/sharelatex/web-sharelatex/commit/30d86fe532f0009557932566edec758117fc6fc3

**Comment by jpallen** [comment]
Thanks, this is part of our custom latex worker at https://github.com/sharelatex/ace/blob/latex-syntax-check/lib/ace/mode/latex_worker.js. We ignore commands if don't know whether it should accept _ or not, like \ref, but it appears we don't ignore `[..]` arguments and we should also.

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
