### ISSUE TITLE
[Bug] Review panel does not preserve line breaks in the comments

### ISSUE THREAD

**Issue by alexpolozov** [overleaf/web#486]
Looks like the comment text is inserted in the generated HTML markup verbatim. This means that all line breaks in the original comment disappear in the output, since HTML ignores them.
Instead, they should be converted into `<br>` or something.

**Comment by jpallen** [comment]
Thanks, this is something we should fix, I agree.

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
