### ISSUE TITLE
Add nodemailer-sendmail-transport to send mails

### ISSUE THREAD

**Issue by xoxys** [overleaf/web#556]
Add nodemailer-sendmail-transport as an option to send mails. For docker environment maybe this is not relevant but if you deploy sharelatex on a host by hand you can use the mail transport from the host (exim, postfix, ...) This prevents users to configure a mail gateway twice.

I have done a basic implementation on my running environment. If you like the idea i can make a PR for this.
Implementation looks like these steps:
* add nodemailer-sendmail-transport to web/packages.js
* add this to web/app/coffee/Features/Email/EmailSender.coffee
```
      else if Settings?.email?.parameters?.SendMailEnabled?
          logger.log "using sendmail for email"
          nm_client = nodemailer.createTransport({
              sendmail: Settings?.email?.parameters?.SendMailEnabled,
              newline: Settings?.email?.parameters?.SendMailNewline,
              path: Settings?.email?.parameters?.SendMailPath
          })
```
* adjust config file to fit the variables

This is a quick and dirty solution but i think its easy to brim this in a clear format.

**Comment by jpallen** [comment]
This sounds like a good PR to put together, thanks. Can you use `sendMailEnabled` rather than `SendMailEnabled` though please?

**Comment by xoxys** [comment]
Sure. I will prepare a PR for this.
