### ISSUE TITLE
[Enhancement] New hotkey to open the word count interface

### ISSUE THREAD

**Issue by yxliang01** [overleaf/web#559]
This is useful. It would be cool if this can be implemented.

Thanks!

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
