### ISSUE TITLE
Old Images in LastPass chrome extension

### ISSUE THREAD

**Issue by tomcoombs87** [overleaf/web#573]
No idea if this is on your end or with LastPass, but they have the old icon. I've tried the [LastPass suggested actions](https://lastpass.com/support.php?cmd=showfaq&id=766), but no change...
 
![lastpass-oldlogo](https://user-images.githubusercontent.com/13438143/29003211-5ed13ef6-7aaa-11e7-82c7-a1eb6e979cb7.PNG)

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
