### ISSUE TITLE
Go to PDF location in code is disabled when using Knitr (.Rtex)

### ISSUE THREAD

**Issue by mikeschaekermann** [overleaf/web#581]
It seems like this useful feature does not work when I use the .Rtex extension to enable Knitr for my draft. Is this an easy problem to solve? Would be super useful if it worked! :)

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
