### ISSUE TITLE
Folder file count not refreshed.

### ISSUE THREAD

**Issue by awasthi** [overleaf/web#600]
I was haviing several project in my account. I tagged these to different folders. After deletion of most of the project I left with two in list. But, Count (IN RED BLOCK in attached figure) under Folder section is not updating. It is showing 21 while I have only 2 projects in my account now.
![sharelatexbug](https://user-images.githubusercontent.com/124547/30241398-423c8708-95a0-11e7-8187-e44893af0270.png)

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
