### ISSUE TITLE
Feature Request: Shortcut for 'open file / folder' dialog

### ISSUE THREAD

**Issue by fahu** [overleaf/web#607]
In the most editors (Atom, VSCode, Sublime, ...) and IDEs there is a shortcut to open a small dialog to search for files or directories. The command is on all editors the same: cmd-shift-o for mac, ctrl-shift-o for windows and linux. 

This command would be very useful when you're having bigger latex projects with multiple file to switch fast between files.

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
