### ISSUE TITLE
Cursor offseted to right way too much on Firefox 57 (beta)

### ISSUE THREAD

**Issue by jfranciscosousa** [overleaf/web#610]
![bug](https://user-images.githubusercontent.com/9119466/31080424-93ccc7d0-a780-11e7-9bee-accc1bf7a30d.gif)

As you can see the cursor is offseted to the right of the text, it happens on Firefox 57 (still beta though). I don't know if it works OK in regular stable Firefox (haven't tested yet) but it works on Chrome.

It bugs out on both my Ubuntu and Windows 10 machines (all in Firefox 57), works OK in Google Chrome and Chromium.

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
