### ISSUE TITLE
Show the name of the tex file currently being edited at the top of the page

### ISSUE THREAD

**Issue by staslev** [overleaf/web#612]
This is super useful when dealing with a multi-file document such as a thesis, a dissertation, a book, etc.

For example, when working on more than one file at a time, things get very confusing after you hop between them for a while and loose track of which one is it that you are currently editing.

I believe this is a known problem in the multi-file editors, and showing the name of the actively edited file at the top should resolve this issue.

Love your product, keep up the good work!

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
