### ISSUE TITLE
Project wide file search

### ISSUE THREAD

**Issue by staslev** [overleaf/web#613]
It would be great if one could search the entire project and not just the active file.

**Comment by marisancans** [comment]
I cant seem to figure out how to search the whole project for a specific word. Is this really a problem for 3 years now? Or I just cant find how to do it.

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
