### ISSUE TITLE
web-sharelatex crashes if too much editable text in project

### ISSUE THREAD

**Issue by Joehein** [overleaf/web#615]
this report may help an admin of sharelatex in some annoying situation of a web-sharelatex crash:

web-sharelatex crashes (only this and not clsi or the doc-updater etc.) if a user has too much editable text, and ignores the warnings, on any attempt to recompile the project. Since the project starts compiling if opened in the browser, it will not be possible by an ordinary user to delete some of the text files, since web will crash immediately.  

To recover as much as possible fom this project, I opened it - web crashed - I restarted web staying on the same website of the opened project - getting reconnected - now there is no recompile since the project is already open - so you can delete some of the text files (You can use a different extension to be recognized as a binary... so it is posible to download and upload as binary again and no information is lost...except the file extensions)

What is really the source of that crash? What is the principal limitation for the editable text per project?
(I know there is a 2 MB limit per text file but what is the limit for many files per project?)

Unfortunately I did not made log file copy (I'm sorry), I only remember an error message about an unwriteable header... 
but anybody is invited to make a test:
simply upload some 1 MB text files (because 2 MB is the accepted limit, extension must be .tex, .txt, ... etc, in total I had about 20-30 MB), Ignore the warning about too much editable text and try -> Recompile
BUT YOU WILL BE WARNED: WEB-SHARELATEX MAY CRASH DOING THIS! 
That's why it would be good to have a connection open to your server with the permission to restart it!

A solution to avoid the crash would be to disable the Compile button (and the recompile at project load) if there is too much editable text in the project, what is obviously recognized already. Meanwhile you should inform your users not to ignore warnings :-) and to act immediately - the right way, hopefully!

I'm running sharelatex from the master-branch from March 18, 2017 under node 6.11.1 in Linux with a minor hack to allow running pythontex in sharelatex, what was nicely stable until that time.

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
