### ISSUE TITLE
[Enhacement] Make the spell check ignore keywords

### ISSUE THREAD

**Issue by cladelpino** [overleaf/web#616]
Since I write in Spanish, I set my "Spell Check" to spanish. This is a very nice feature of ShareLatex, but it's quite annoying that it then marks parameters as wrong. For instance: 

\documentclass{article}

marks "article" as a mistake. 

I can see how this can be quite hard to implement (i e keeping a list of global keywords), but it would be a nice enhacement.

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
