### ISSUE TITLE
Will comment function come to Community Editon 

### ISSUE THREAD

**Issue by CordlessWool** [overleaf/web#617]
Hi,

are there any planes to bring the commend function, is use able on sharelatex.com to the Community Editon, because I will use sharelatex for my master thesis, so I set it up on my sever, but missing the comment function, which is very important.

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
