### ISSUE TITLE
Feature request | Mendeley integration per project instead of per ShareLatex account.

### ISSUE THREAD

**Issue by TiesdeKok** [overleaf/web#618]
With multiple research projects with different co-authors it is important to be able to specify a Mendeley account that is specific to each project, instead of only being able to integrate one Mendeley account.

Our general work-flow is to create a shared Mendeley account for each project, this keeps all the references nicely organized per project. Currently this approach is not compatible with ShareLatex because the Mendeley account is linked at the ShareLatex account level instead of the project level.

**Comment by victorvanpelt** [comment]
This is exactly what we need. I was thinking about requesting this a while ago. I hope they strongly consider this feature.

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
