### ISSUE TITLE
[Feature request] switching panes (source : PDF <-> PDF: source).

### ISSUE THREAD

**Issue by darkrsw** [overleaf/web#623]
Hi,

Currently, the web view of sharelatex shows panes in sequence of [file tree] - [source] - [PDF output]. Although PDF full screen mode is available, it is also necessary to provide a feature of rearranging the panes such as [file tree] - [PDF output] - [source].

Regards,
Dongsun.

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
