### ISSUE TITLE
[Feature request] Add character count statistics

### ISSUE THREAD

**Issue by MartinoMensio** [overleaf/web#625]
In the "word count" dialog, it would be useful to have the character count of the resulting document. Sometimes it happens that to write some documents you are imposed a limit on the character level.

This feature exists on MS Word, GDocs.

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
