### ISSUE TITLE
Go to declaration / definition

### ISSUE THREAD

**Issue by myfairsyer** [overleaf/web#627]
When I look at someone else's document or template I'd love to be able to find out where a certain command comes from without trial and error.
So a first step would be to maybe display the location (file/package/...) on hover.
Another to directly offer jumping to the declaration/definition.

<details>
<summary>SEO</summary>
go to definition <br>
go to declaration <br>
go to the definition <br>
go to the declaration <br>
jump to definition <br>
jump to declaration <br>
jump to the definition <br>
jump to the declaration
</details>

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
