### ISSUE TITLE
Jump over words and spaces at once

### ISSUE THREAD

**Issue by quantenProjects** [overleaf/web#628]
It would be very nice if the courser would jump over the next word and space when you press ctrl+arrowKey in the source editor.

At the moment this key combo only jump over the next word or space. So when you want to navigate through the text you have to press the arrow key twice as often compared to other editors (kate or LibreOffice.

I often have to rearrange my sentences and this change on this wonderful tool would make it much faster.

**Comment by vvv214** [comment]
Totally agree! Having to jump twice is actually very annoying during editing.

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
