### ISSUE TITLE
More unique name for downloaded PDF

### ISSUE THREAD

**Issue by lindhe** [overleaf/web#629]
I've chosen to have my native PDF reader instead of the built in one, which I think is a great feature of you to offer. I do however work on multiple projects at once, and so it's rather unhelpful that the default name of the pdf I get is "output.pdf". This makes it so I need to rename/move the file, or the other project will be overwritten. It would be nice if it at least padded with the title or something.

Example: project1.pdf

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
