### ISSUE TITLE
GitHub Sync: Git rename/delete failed

### ISSUE THREAD

**Issue by songjinghe** [overleaf/web#630]
If I push git commits which contains file rename (i.e. `git mv A A_after_rename`) or file deletion `git rm XXX` to Github repo, and pull them from sharelatex project (which sync with that github repo), then sometimes (happens 3 times in 4 of such kind of commit) the operation is not applied, i.e. the file is not renamed nor deleted. So I have to manully rename/delete that file.

This is strange, can anyone come up what is going on and how to solve the problem?

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
