### ISSUE TITLE
Copy Files and Folders

### ISSUE THREAD

**Issue by dfelder** [overleaf/web#631]
Hey guys, it would be great if it was possible to copy directories and files in the web interface. In my case it would be useful for automatic latexdiffs against a previous version, but I bet there are plenty use cases.

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
