### ISSUE TITLE
[Feature Request] Hot keys - typewriter font, emphasis

### ISSUE THREAD

**Issue by pluskal** [overleaf/web#633]
Currently, web hotkeys contain limited support for shortcuts decorating the text. It would be great if default instance supported also shortcuts for ```\texttt{}``` and ```\emph{}``` as well. 

Thanks in advance, Jan

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
