### ISSUE TITLE
Track changes markup with dark themes 

### ISSUE THREAD

**Issue by dfelder** [overleaf/web#634]
![image](https://user-images.githubusercontent.com/556324/38417935-a0eab790-399a-11e8-8072-584cdcf2bb81.png)

The highlighting of changes is hard to distinguish in front of dark themes like monokai.

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
