### ISSUE TITLE
Babel package warning

### ISSUE THREAD

**Issue by vancanhuit** [overleaf/web#635]
I'm trying using ShareLatex to create Vietnamese documents. When I included the Vietnamese babel package and then compiled tex file, it worked fine but a warning appeared: 
![untitled](https://user-images.githubusercontent.com/18382438/38684075-159a9fda-3e99-11e8-91a4-b36be9d14a6d.png)

Why this warning message appear? Here is my demo tex file:

```tex
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[vietnamese]{babel}

\title{Thử nghiệm soạn thảo tiếng Việt trên sharelatex.com}
\author{Đinh Văn Cảnh}

\begin{document}

\maketitle

\section{Giới thiệu}
Soạn thảo latex trên sharelatex.com.

\end{document}
```

And compiled PDF:
![untitled-1](https://user-images.githubusercontent.com/18382438/38684470-f7bcc0aa-3e99-11e8-9217-49a9a1995338.png)

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
