### ISSUE TITLE
[Feature Request] Detex integration

### ISSUE THREAD

**Issue by arnthorg** [overleaf/web#636]
Hi, 

English is my second language and as such my grammar is not the best. I've long wanted an integration between sharelatex and grammarly or better grammark. 

As a workaround it's possible to use detex to strip of all the latex headers in the document and input manually into the grammar tools. 

So that brings me to my request: is it possible to integrate detex into the web version of sharelatex? Is there maybe another way of getting the pure text from the document? Copying and paste'ing from the PDF is suboptimal because of line breaks. 

Thanks,
Arnþór

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
