### ISSUE TITLE
Incorrect behaviour of ~ in Vim mode

### ISSUE THREAD

**Issue by lindhe** [overleaf/web#637]
When I'm in Vim, `~` will switch the case for the letter which is under the cursor (and then place the cursor one character to the right). But your Vim emulator takes one step to the right _and then_ switches case. So the wrong letter gets switched. Rather annoying, while it does not really break anything.

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
