### ISSUE TITLE
PDF output is different from running latexmk locally - related to subfiles package

### ISSUE THREAD

**Issue by samwalls** [overleaf/web#638]
I have a large document with multiple sub-latex files using `subfiles` (some subfiles have other subfiles), using the `tufte-latex` class, as well as `biblatex` citations.

On my own machine the document compiles as I want it to with `latexmk --pdf main.tex`, however, on sharelatex, I get _most_ of the document, but with some things missing. The most puzzling thing is that _one_ of the subfiles is included in the output, but all others aren't. I've searched the log output and for each of my subfile sections and the only thing I can find related to them is something of the sort (paraphrased):

```
biblatex compile [src/my-subfile]
empty bibliography, skipping
```

Essentially, it's as if the content of the subfile (which contained references, and would be used in the bibliography) is not being used _at all_.

Now, if I go to each of my subfiles individually (same project), I can compile and view previews for each of them, and everything works. The most annoying part is that I have one subfile that has _multiple other subfiles_ and _that also works!_

Why might the main document not be including these subfiles properly?

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
