### ISSUE TITLE
Login redirects to /sso/login, which is not found

### ISSUE THREAD

**Issue by crockeea** [overleaf/web#641]
When I'm at the login page for my ShareLaTeX server (/login?redir=%2Fproject%<hash>), I enter my username/password and hit "Login". This takes me to **/sso/login/**, resulting in a "Not Found" ShareLaTeX page. If I remove the /sso/login, I get taken to the main page, logged in as expected. The question is: why am I taken to a non-existent page instead of my main home page immediately upon login?

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
