### ISSUE TITLE
Large Bib files cause project to hang

### ISSUE THREAD

**Issue by crockeea** [overleaf/web#642]
The attached example causes ShareLaTeX to eventually crash both Chrome 66 and Firefox 60 (though it compiles fine on my local machine with TeXStudio). This may or may not be related to #615. When this project is loaded, ShareLaTeX begins to compile, but it takes forever. Eventually, the page completely freezes and (at least in Chrome) I get a message saying that the page has crashed. During this time, the page has extremely high resource utilization (as measured by the Chrome task manager). Note that the *server* continues to function for other users on other projects, and I don't see anything in the logs that indicates anything suspicious.

The problem appears to be this particular bib file (available from https://cryptobib.di.ens.fr/) in combination with biber. If I specify [backend=bibtex] to biblatex, ShareLaTeX happily compiles this project.

[browser_crash_mwe.zip](https://github.com/sharelatex/web-sharelatex/files/2074201/browser_crash_mwe.zip)

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
