### ISSUE TITLE
Error comunicating with the analytics service

### ISSUE THREAD

**Issue by dtu-compute** [overleaf/web#645]
This bug prevents one from opening projects.

When using the sharelatex docker image I get
```
Could not connect to websocket server :(
```
when opening a project. Looking in `/var/log/sharelatex/web.log` I see

```
{"name":"web-sharelatex","hostname":"d263247804dd","pid":17,"level":40,"msg":"Error comunicating with the analytics service. Will try again attempt 4 in 16000ms","time":"2018-06-22T08:55:14.562Z","v":0}
undefined { body: { event: 'announcement-alert-dismissed' },
  json: true,
  method: 'POST',
  timeout: 1000,
  url: 'http://localhost:3050/user/5b2cb90754aa3301c1ff90c6/event/last_occurrence',
  maxAttempts: 5,
  retryDelay: 5000,
  fullResponse: true,
  promiseFactory: [Function: defaultPromiseFactory] }
{"name":"web-sharelatex","hostname":"d263247804dd","pid":17,"level":50,"user_id":"5b2cb90754aa3301c1ff90c6","err":{"message":"connect ECONNREFUSED 127.0.0.1:3050","name":"Error","stack":"Error: connect ECONNREFUSED 127.0.0.1:3050\n  at Object._errnoException (util.js:1022:11)\n  at _exceptionWithHostPort (util.js:1044:20)\n  at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)\n","code":"ECONNREFUSED"},"msg":"error getting last occurance of event","time":"2018-06-22T08:55:16.570Z","v":0}
{"name":"web-sharelatex","hostname":"d263247804dd","pid":17,"level":40,"msg":"Error comunicating with the analytics service. Will try again attempt 5 in 32000ms","time":"2018-06-22T08:55:22.561Z","v":0}
```
Searching for "comunicating" in the source gives this file

https://github.com/sharelatex/web-sharelatex/blob/master/app/coffee/Features/Analytics/AnalyticsManager.coffee

**Comment by EoleDev** [comment]
I found a temporary fix : 
 - you launch the docker sharelatex image.
 - open a terminal inside the docker instance : docker exec -ti sharelatex /bin/bash
 - edit /var/www/sharelatex/web/config/settings.defaults.coffee and comment out the two line about analytics endpoint
 - create a new image from the running endpoint (I used portainer for that)
 - relaunch from the new image.

In the source code, if the analytics endpoint is not configured, it just skip it's part.

**Comment by das7pad** [comment]
I went down that rabbit hole as well. AFAIR some invocations are guarded with checks on `settings.apis.analytics`, some just on `settings.apis.analytics.url`. Other locations call it straight, e.g. the login IIRC.

A fix for analytics should be this patch https://github.com/das7pad/web-sharelatex/commit/15148c1dc80735259677491b941ce4792884a5fd in addition to it's parent for the acceptance test.

In my config I have something like this:
```
module.exports = settings =
    # ...
    apis:
        analytics:
            enabled: false
            url: undefined
    # ...
```

My `jenkins` branch has all of them patched, the last analytics event in sentry (error reporting) came in May 31. This is a week after I deployed the mentioned patch, so there might be another patch related to analytics.

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
