### ISSUE TITLE
Update user/personal_info

### ISSUE THREAD

**Issue by lpla** [overleaf/web#648]
Hi. Testing v2.overleaf.com and sharelatex.com I ended at user/personal_info (in both sites) and I wasn't able to update that information. How is supposed to be that information updated? What is that information used for now?

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
