### ISSUE TITLE
Enterprise website broken

### ISSUE THREAD

**Issue by hr87** [overleaf/web#650]
Your website for the on-site supported version is broken. This makes it hard to sell this project to any manager.

https://www.sharelatex.com/i/university/onsite

Used browsers to check: Firefox and Chrome mobil

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
