### ISSUE TITLE
Upgrade ace version

### ISSUE THREAD

**Issue by ghost** [overleaf/web#652]
ShareLaTeX currently uses an outdated version (v1.2.5) of the Ajax.org Cloud9 Editor (ace) which has many bugs including https://github.com/sharelatex/web-sharelatex/issues/611

Please upgrade to the newest version which is 1.4.1 currently.

**Comment by das7pad** [comment]
Fixed in https://github.com/sharelatex/web-sharelatex/commit/5607f8d223564314a762106e8fee7b243de82cbc by @paulojreis

**Comment by jdleesmiller** [comment]
Thanks, ace upgrade has indeed been completed.
