### ISSUE TITLE
Bundle administrator asked to remove themselves from Professional Group Plan subscription

### ISSUE THREAD

**Issue by mans0954** [overleaf/web#654]
See https://app.frontapp.com/open/cnv_xyqo99

Steps to reproduce:

* Admin
  * Find user in user admin https://www.sharelatex.com/admin/user
  * Delete any existing subscriptions
  * Create a new subscription according to https://www.overleaf.com/read/zbbjxqrgqrgd#/52881380/
* User
  * User logs in 
  * Go to `Account` / `Account Settings` / `Manage Group`
  * User adds their own e-mail address to group
  * User receives confirmation e-mail and follows link
  * User sees a message `You already have a personal subscription, would you like us to cancel this first before joining the group licence?`

This message seems to me to be an error, as admin has already cancelled the personal subscription.

If the user clicks `Not Now` then joining the group proceeds as planed. If they (not unreasonably) click `Stop Your Subscription` then it fails silently (an error is logged to the browser's java console) and their group membership is not confirmed.

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
