### ISSUE TITLE
Upload Zipped Project broken

### ISSUE THREAD

**Issue by filipre** [overleaf/web#655]
Hi, 

it seems like it is not possible to upload *.zip files anymore. One of my projects has thousands of files in it and I simply cannot upload them to Sharelatex nor to v2Overleaf (which seems to use the same technology behind it). Neither it is possible to upload folders (see https://github.com/sharelatex/sharelatex/issues/423)

<img width="606" alt="screen shot 2018-08-18 at 12 38 10" src="https://user-images.githubusercontent.com/8502198/44298470-f797d980-a2e3-11e8-98c8-6f8a0e1c673a.png">

Obviously the project has been zipped correctly. How can I upload my project to Sharelatex? Dropbox and Github are not an option.

Greetings
René

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
