### ISSUE TITLE
Add Environment Variable for AWS_REGION for use with SES

### ISSUE THREAD

**Issue by crockeea** [overleaf/web#656]
## Problem

When using SES, there doesn't seem to be a way to change the region from 'us-east-1'. When SES is running in a region other than 'us-east-1', SES refuses to send emails.

Please add a way to configure the AWS region for SES.

## Logs and errors

For example, I'm unable to reset my password. I get a red box with "Cannot send email".

Web.log includes:

"MessageRejected: Email address is not verified. The following identities failed the check in region US-EAST-1:"

**Comment by crockeea** [comment]
Workaround:

1. Run the docker container.
2. `$ docker exec -it sharelatex /bin/bash`
3. `$$ cd /etc/sharelatex`
4. `$$ vim settings.coffee`
5. Go to line 408
This should put you in the vicinity of 
```
                        #AWS Creds
                        AWSAccessKeyID: process.env["SHARELATEX_EMAIL_AWS_SES_ACCESS_KEY_ID"]
                        AWSSecretKey: process.env["SHARELATEX_EMAIL_AWS_SES_SECRET_KEY"]

                        #SMTP Creds
                        host: process.env["SHARELATEX_EMAIL_SMTP_HOST"]
                        port: process.env["SHARELATEX_EMAIL_SMTP_PORT"],
                        secure: parse(process.env["SHARELATEX_EMAIL_SMTP_SECURE"])
                        ignoreTLS: parse(process.env["SHARELATEX_EMAIL_SMTP_IGNORE_TLS"])
```
6. Add the lines
```
\t\t\t#SES Creds
\t\t\tregion: "us-west-2"
```
Note that you must use three tabs, not spaces.

My final settings.coffee file looks like:
```
                        #AWS Creds
                        AWSAccessKeyID: process.env["SHARELATEX_EMAIL_AWS_SES_ACCESS_KEY_ID"]
                        AWSSecretKey: process.env["SHARELATEX_EMAIL_AWS_SES_SECRET_KEY"]

                        #SES Creds
                        region: "us-west-2"

                        #SMTP Creds
                        host: process.env["SHARELATEX_EMAIL_SMTP_HOST"]
                        port: process.env["SHARELATEX_EMAIL_SMTP_PORT"],
                        secure: parse(process.env["SHARELATEX_EMAIL_SMTP_SECURE"])
                        ignoreTLS: parse(process.env["SHARELATEX_EMAIL_SMTP_IGNORE_TLS"])
```
7. Save and quit vim
8. `$$ exit`
9.  Saves the changes you made to a new docker image
`$ docker commit sharelatex sharelatex-regionalized`
10. Stop the running container
`$ docker stop sharelatex`
11. Remove the running container
`$ docker rm sharelatex`
12. Restart the docker image
`$ docker run ...... --env SHARELATEX_EMAIL_FROM=foo@bar.com --env SHARELATEX_EMAIL_DRIVER=ses --name sharelatex sharelatex-regionalized`

**Comment by MalteJ** [comment]
is this bug still not fixed??

**Comment by dhaley** [comment]
+1 for merging this pull request and including in Sharelatex Pro v. 2.5.1.

We're getting this error because of the improperly set region:

MessageRejected: Email address is not verified. The following identities failed the check in region US-EAST-1: someone@gmail.com, no_reply@nrelcloud.org\n      at Request.extractError (/var/www/sharelatex/web/node_modules/aws-sdk/lib/protocol/query.js:47:29

This is because we can only relay mail through the us-west-2 region.
