### ISSUE TITLE
No Mongo SSL connection via SSL and certificate validation possible

### ISSUE THREAD

**Issue by Joehein** [overleaf/web#657]
**The problem:** A connection to the mongo database via SSL with server certificate validation requires additional settings in the options argument of Mongojs' or Mongoose' MongoClient (the used modules already support this!). At the moment there is no such Option setting in the Settings.coffee possible. 
**Possible solution:** Because the different parts of ShareLatex make one or even more than one connection to Mongo (more than ten in total) a secured connection to the database requires such an additional central setting. As a request to the developer I would suggest to add the possibility to change the Mongo-Connector Options Object in addition to the Settings.mongo.url in the Settings.coffee (as well as in the default settings). For somebody who knows where all the Mongo-connections are found (unfortunately I do not) in the software this should be an easy task to solve, what helps to improve security a lot without violating down compatibility. 
**Background:** Running mongod without authentification, what is nonsense without SSL (exept the database can only be reached locally, what is not possible with a replicating or sharding server), what is nonsense without a server certificate is a high security risk or even not acceptable! 
**Request:** Please leave a comment if somebody intends to do this or knows how to solve this differently. Thank you!

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
