### ISSUE TITLE
feature: section navigation in editor, recognize TODO comments

### ISSUE THREAD

**Issue by pizdjuk** [overleaf/web#672]
It would be great to have a navigation in editor, and that an editor would recognize the TODO comment. Just like texstudio does.

**Comment by samuelgfeller** [comment]
I agree would be pretty useful

**Comment by arteagac** [comment]
Yes, it would be fantastic to have a Navigation feature based on headings or sections. It would make it easier to work with long documents.

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
