### ISSUE TITLE
feature request for arXiv integration

### ISSUE THREAD

**Issue by vainaijr** [overleaf/web#678]
hello,

is it possible to integrate overleaf with arXiv, so that I would be able to open LaTeX file from arXiv directly in overleaf.com, I would not have to download it to my local machine, and then upload it to overleaf.com, and that also it gives error zip file invalid.

**Comment by jdleesmiller** [comment]
In fact Overleaf has an API that would support that use case, so this would be a request for the arXiv team. https://www.overleaf.com/devs

**Comment by vainaijr** [comment]
here is reply from arXiv

"That is an interesting idea.

I would also suggest that you bring up this idea with Overleaf. They could allow users to enter an arXivID on their site and they would fetch, extract, and display the LaTeX source. That would be similar to how some journals fetch author TeX files from arXiv and require no additional development effort on arXiv's end.

Then if that tool was setup on Overleaf's end the request could come back to us to consider adding a link from the arXiv source download page that could pass the arXivID to Overleaf or other third party service handle it from there. There may be questions from Overleaf's side on how to best set it up and we would be happy to talk with them.

I just think the first steps should be initiated by Overleaf."
