### ISSUE TITLE
Word Count ambiguity

### ISSUE THREAD

**Issue by aseyffert** [overleaf/web#679]
The Word Count feature isn't clear about what is included in the "Total Words" statistic. This ambiguity can lead (and has in my case) to effectively erroneous word counts being delivered to the user. Specifically, many journals (e.g., The Astrophysical Journal Letters; https://aastex.aas.org/ApJL/countwords.html) define a word as "a white space delimited object," which typically includes inline math enclosed in $'s.

Since overleaf supports directly uploading a manuscript to many journals, this ambiguity should probably be dealt with.

## Suggested Solution
Add a setting to toggle between an "inline-math-included" mode and a normal "non-math only" mode for word counting, with corresponding verbosity in the Word Count window to ensure the user is aware. Perhaps implement the latter as a dismissible note/warning.

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
