### ISSUE TITLE
Go to PDF location in code points to the wrong code location when document includes a watermark.

### ISSUE THREAD

**Issue by ekoraytascilar** [overleaf/web#680]
## Expected Behaviour
Double clicking on a location in pdf expected to point to the code location that generated the line

## Observed Behaviour
Double clicked area on pdf is the screenshot below
![grafik](https://user-images.githubusercontent.com/10676301/63439163-dce3cd80-c42d-11e9-9ce3-33a947025ca0.png)

Code that overleaf points is below

![grafik](https://user-images.githubusercontent.com/10676301/63439294-0ac91200-c42e-11e9-9238-9d889b388119.png)

Code that overleaf is supposed to point is below

![grafik](https://user-images.githubusercontent.com/10676301/63439411-41069180-c42e-11e9-88f6-c53e7fec545f.png)

## Context
What I observe is that the problem is resolved when the watermark is removed. ignoring watermark while directing from pdf to code might solve the issue.

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
