### ISSUE TITLE
Ctrl+F Search, with  LaTeX comments filtered out

### ISSUE THREAD

**Issue by bastianilso** [overleaf/web#682]
During scientific work, we often end up with a lot of commented out paragraphs and text (with percentage mark %). When we search for occurences of words with Ctrl+F, these comments receive hits. I therefore suggest some sort of filter, which could toggle whether to search within LaTeX comments or not.

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
