### ISSUE TITLE
[Feature] Git version control for comments

### ISSUE THREAD

**Issue by tvercaut** [overleaf/web#686]
The "Add comment" feature of overleaf is great for collaborative work. It would be even better if one had access to the comments history when pulling the project through git. I currently couldn't find it, so let me know if I misunderstood.

This feature probably relates to the issue documented in https://github.com/overleaf/overleaf/issues/552

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
