### ISSUE TITLE
Grouping in regex is not working in Vim mode

### ISSUE THREAD

**Issue by gkevinyen5418** [overleaf/web#687]
## Steps to Reproduce

1. Have some text like `123456` 
2. Write some regex with groupings `:%s/1\(.*\)6/\1/g`

## Expected Behaviour

The text become `2345`

## Observed Behaviour

No matches

**Comment by ShaneKilkelly** [comment]
Hi! as far as I can tell, this feature isn't supported by [ace.js](https://ace.c9.io/), which is the foundation of our editor technology.
