### ISSUE TITLE
Acceptance tests with non OSS dependency

### ISSUE THREAD

**Issue by das7pad** [overleaf/web#692]
The `UserMembershipAuthorizationTests` [1] depend on the `metrics` module. Please consider moving it into the acceptance tests of said module.

---
[1] https://github.com/overleaf/web/blob/c6bf5eb8e161d2a1017c06c38ac5837974872d70/test/acceptance/src/UserMembershipAuthorizationTests.js

**Comment by ShaneKilkelly** [comment]
Good catch, I'll open an internal ticket to resolve this. Thanks! :tada:

**Comment by timothee-alby** [comment]
Thank you for raising this, now fixed :)
