### ISSUE TITLE
Local installation exposes internal information by loading external libraries

### ISSUE THREAD

**Issue by panholzerp** [overleaf/web#706]
## Steps to Reproduce

1. Open local Sharelatex/Overleaf installation
2. Open browser's developer console (e.g. Chrome DevTools -> Network)
3. Observe requested domain when reloading the page

## Expected Behaviour
All libraries are loaded onto the local installation and web sessions do not issue requests to external entities.

## Observed Behaviour
The local installation loads libraries from external sources like google.

## Context
This is an issue because it
1) exposes internal URLs to external entities
2) it allows external entities to track usage of internal resources (this is also an issue with the cloud installation btw.)
3) it raises the chance that malicious code is loaded
(this can of course also happen while loading the library to the local installation for static integration, but this would be easier to detect and more difficult to do only for specific victims. I.e. when the library is loaded externally, the external entity could choose to hand out different versions depending on the Referer).

## Technical Info
N/A

* URL:
* Browser Name and version: N/A
* Operating System and version (desktop or mobile): N/A
* Signed in as: N/A
* Project and/or file: N/A

**Comment by ShaneKilkelly** [comment]
Hi there!
This is something we've been considering internally for a while, and we'd like to get to a point where we can have the whole docker container ship with everything it needs included in the box.

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
