### ISSUE TITLE
[Enhancement] Scratchpad for Complex Symbols

### ISSUE THREAD

**Issue by fillantrophy02** [overleaf/web#713]
#### Current Implementation
The current toolbar (when switched to the `Rich Text` interface) only includes basic formatting options (e.g. `Bold` and `Insert Inline Math`).

#### Potential Problems
For the average new user, this is less than ideal. They are not used to LaTeX, don't know the names/commands for all the symbols they use, and are likely working on something rather math heavy, otherwise they would have stuck with Microsoft Word/LibreOffice Writer, etc.

While Overleaf provides actual learning resources to cushion this, constantly looking them up while working on something time-sensitive is probably not the best way or time to learn.

#### Potential Solutions
1. Turn Overleaf into Word with gigantic toolbar and a bunch of symbols you can search through. Personally I think this is a bad idea the absence of which being precisely the thing people appreciate about LaTeX once they get used to it. The search bar makes the interface somewhat more convenient but is not enough on its own. Who know the names of all the symbols they use when they're just starting out? Even experienced users probably stall on this from time to time.

2. A drop-down scratchpad that allows you to jot down the symbol you want and suggests the closest matches as symbols and LaTeX commands. Once you click on one of them, it's inserted into your document. Something like [Detexify](http://detexify.kirelabs.org/classify.html) but integrated into Overleaf for convenience and learning on-the-go. A search bar could be added as well to supplement this. Ideally, the image recognition would be implemented client-side using [TensorFlow.js](https://www.tensorflow.org/js) or one of its alternatives so as to not put extra load on the servers.

I realize that this feature would be a lot of work, but I'm willing to roll up my sleeves. Would you be interested in a pull request for something like this?

**Comment by jjzmajic** [comment]
Not to rush anyone, but any updates/thoughts on this? It would just make life so much easier.

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
