### ISSUE TITLE
GitHub Sync: Renaming the repo leads to minor bugs

### ISSUE THREAD

**Issue by gkevinyen5418** [overleaf/web#714]
## Steps to Reproduce

1. Create an overleaf project
2. Create a github repo from the GitHub Sync tab
3. Rename the repo from github

## Expected Behaviour

The GitHub Sync tab should show
"This project is synced with the GitHub repository at"
with the right repository.

## Observed Behaviour

The name and url shown is incorrect. (github redirects you as long as you don't create another repo with that name though)
The sync itself works fine.

**Comment by mserranom** [comment]
Since this is not a feature part of Overleaf Community Edition please use [overleaf.com contact form](https://www.overleaf.com/contact) to report any issue. Thanks!
