### ISSUE TITLE
Implement Search and Replace Across All Files in a Project

### ISSUE THREAD

**Issue by JeffLCoughlin** [overleaf/web#715]
This is a feature request to implement a Search and Replace functionality across multiple files.  Currently only file at a time can be search-and-replaced, which poses a burden for big projects that use input calls in their main.tex file to separate .tex files for each section, e.g., a long paper or textbook.

**Comment by mserranom** [comment]
Please have a look at https://github.com/overleaf/web/issues/79#issuecomment-613966575

**Comment by JeffLCoughlin** [comment]
Thanks.  Good to have confirmation it is in the backlog.

**Comment by irfanlateefus** [comment]
As mentioned in the #79 comment referenced above, this was originally created on June 17, 2014.
It is going to be 7 years this June. It is insane that Overleaf ignores an important feature request like this.
Overleaf utter disregard for the students and academicians is unbeleivable.
I request the feature and register my protest at this treatment of users.
