### ISSUE TITLE
Resizable review panel or set a relative width for long comments

### ISSUE THREAD

**Issue by cpauvert** [overleaf/web#719]
Hi, 
Thanks for this awesome tool that keeps improving! 

When comments are getting long, they tend to be shrunk in the review panel. Upon inspection, it appears that the width is fixed (cf CSS chunk below). Changing the review panel `div` width to relative would increase the readability of such comments. Furthermore, the ability to resize the review `div` could be even more awesome!

```
.rp-size-expanded #review-panel {
    display: flex;
    flex-direction: column;
    width: 230px;    <-------------------------
    overflow: visible;
    border-left-width: 1px;
}
```

This issue is just an enhancement proposal rather than a bug.
Best, 
Charlie

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
