### ISSUE TITLE
Best way to edit the code

### ISSUE THREAD

**Issue by junoriosity** [overleaf/web#720]
I would like make some changes to the code and see how it works out. However, I have not figured out an efficient and fast way to do this. My best guess so far was to fork this repo, make changes locally and push them. Then I forked the overleaf/overleaf repo, edited the services.js file to use my remote web git and ran

`docker build -f Dockerfile-base -t sharelatex/sharelatex-base .`

`docker build -f Dockerfile -t sharelatex/sharelatex .`

`docker-compose up`

to build the Docker image and use docker-compose to get everything running. However this whole process takes me around 10 minutes for some tiny changes like the insertion of a few characters. Does somebody have a suggestion how to improve that?

**Comment by mserranom** [comment]
To get the fastest feedback loop the best option is to edit the code inside the docker container. Visual Studio code is [quite capable doing that](https://code.visualstudio.com/docs/remote/containers). Once a service file is edited, using `kill` inside the container will trigger a service restart.

**Comment by GCrispino** [comment]
I've been trying to do the same thing but I've never really used Docker. The integration between all of Overleaf's repositories kinda confuses me. If I want to run overleaf/web locally, do I have to clone and build the Docker image for every other Overleaf repository? Are there remote servers to "plug in" for development of just a single repository?

I've been able to build overleaf/web (didn't really use Docker, just npm and the proper version of Node, although I was able build and run bash in the Docker image), but when accessing the local server, it shows me a "Something went wrong" page.

**Comment by mserranom** [comment]
Hi @GCrispino. The integration of the different services is all implemented via Docker: networking, external tools, configuration etc. In order to run Overleaf locally you'd need to replicate the setup defined in `Dockerfile-base` and `Dockerfile`. Probably doable, but far from straightforward.

**Comment by GCrispino** [comment]
Hi @mserranom , thanks for answering! So to run any overleaf service locally (web, for example), one would need to build and run all repositories using Docker, is that right?

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
