### ISSUE TITLE
Review comments dotted line overlap causes confusion

### ISSUE THREAD

**Issue by nicomazz** [overleaf/web#721]
This is an improvement request for something I find annoying.

## Steps to Reproduce
1. Add comments in 3 subsequent lines 
2. Open the one in the middle

## Observed Behaviour
The orange dotted lines overlap, and it is not easy to understand where the clicked comment is anchored

## Expected Behaviour
It would be nice if, when there is one focused comment,  the dotted lines of all the others turn to grey, or reduced alpha, or even disappear. An even better solution might be to not allow lines to overlap at all, but I imagine this is harder to implement.

Here it is possible to see the dotted lines that overlap, inside the red box:
![](https://i.ibb.co/hfJpnsC/issue-overleaf.png)

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
