### ISSUE TITLE
Display orgmode files as regular text files

### ISSUE THREAD

**Issue by MasterOdin** [overleaf/web#722]
For organization of notes with my co-authors, I often use [org-mode](https://en.wikipedia.org/wiki/Org-mode) files. These are regular text files with just special ascii mark-up that when combined with org-mode (or pandoc) converts the file to HTML. Even though they are text files then, overleaf currently does not display them at all, requiring me to download the file to view it separate from overleaf. It would be super useful if it could at least show a preview like txt files do.

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
