### ISSUE TITLE
Context menu in folder tree pane opens twice  

### ISSUE THREAD

**Issue by vyrwu** [overleaf/web#725]
## Steps to Reproduce
1. In the folder tree, click hamburger menu associated with a folder to open a context menu.
2. While the context menu is open, point the cursor at the folder item and right click (two finger soft-click on Mac).
3. You will see context menu opened twice:
![Screenshot 2020-08-20 at 14 47 10](https://user-images.githubusercontent.com/23533231/90772132-8638fa00-e2f4-11ea-8f2d-99790d2146af.png)

## Expected Behaviour
Only the latest invoked menu should be visible. Other menus should close on opening the new one to follow users intent.

## Observed Behaviour
Context menu opens twice.

## Context
It's clearly unintended behaviour so I decided to report it.

## Technical Info
* URL: https://www.overleaf.com/project/5e47fc03580a4b000101805f
* Browser: Google Chrome Version 84.0.4147.125 (Official Build) (64-bit)
* Desktop OS: macOS Catalina version 10.15.5 (19F101)

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
