### ISSUE TITLE
[feature request][enhancement] default monospace font in editor

### ISSUE THREAD

**Issue by janpf** [overleaf/web#726]
adding a third font in the font family dropdown, which uses the browser provided "monospace" default font.
Thereby a user can use their own font by setting it in the browser settings.

it's as easy as - upon selection - setting the css attribute to:
`font-family: monospace;`

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
