### ISSUE TITLE
online pdf search does not function correctly

### ISSUE THREAD

**Issue by nathanielvirgo** [overleaf/web#732]
If I view the pdf (in Chrome, on a Mac) and press CMD-F, I see the browser's default text search function. However, it doesn't function correctly - it seems to only search what can currently be seen on the screen, not the whole document. This makes Overleaf somewhat awkward to use sometimes, and is misleading because the search function appears to work, but doesn't.

## Steps to Reproduce

1. Open a project containing a relatively large amount of text (several pages)
2. Click "PDF" to view the PDF file. Due to poor eyesight I don't use multiple panels, so the pdf occupies the whole screen, except for the side bar on the left.
3. Press CMD-F to search the document, while viewing the pdf rather than the source
4. Search for a word that appears in the document, but not on the first few pages.

## Expected Behaviour

I would expect that if the word is contained anywhere in the document, the search function will scroll down and find it.

## Observed Behaviour

If the word is found in the document within a page or two of what's currently visible, then the search functionality will work as it normally would for any web page. However, if the word only appears in a much later part of the document, it simply won't find it - the search bar shows "0/0", as if it wasn't in the document at all. However, if you then scroll down so you can see the word and search again, then it finds it.

Additionally, if the term appears both on the first few pages and later in the document, the search function will only find the first few instances and then cycle back to the start, as if those were the only instances in the document.

## Context

This has sometimes made me think something was not mentioned in my document when in fact it was. Other times it has just proven a bit awkward, since if I want to quickly read all the places where something is mentioned I have to download the pdf and search offline.

I know that overleaf has its own search function, which is accessed by pressing CMD-F while viewing the source. However, I rarely want to search the source directly - I generally want to view what I'm searching for in context in the pdf first, before deciding whether to edit it.

It's also a bit misleading that CMD-F does pop up a search dialog in the pdf file, but it does't function correctly - it would be better if it didn't appear at all.

## Technical Info

* URL: n/a (overleaf.com)
* Browser Name and version: Chrome version 85.0.4183.102
* Operating System and version (desktop or mobile): desktop, OS X 10.11.6 (the machine is old)
* Signed in as: [the same as my github username] at gmail
* Project and/or file: any

**Comment by das7pad** [comment]
We are lazy loading parts of the PDF file as the user scrolls in the PDF viewer. As a work around you can use the _native_ PDF viewer of your browser. The native viewer will load all of the PDF file at once. In my testing with Chromium this allowed me to find key words at the end of a large PDF.

There is an option in the menu of the editor for switching between the two PDF viewers. Be sure to click on the PDF before initiating a search -- the editor and the pdf viewer run in different contexts.

_Note that the sync-to-code and sync-to-pdf features will not work. The native viewer will also forget where you left off and go back to page 1 when re-compiling._

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
