### ISSUE TITLE
Expired token when mail address contains upper case characters

### ISSUE THREAD

**Issue by dvmc** [overleaf/web#741]
## Steps to Reproduce

1. Register a new user (`admin/register`) for the mail address `Alice@example.com`, matching the case.
2. Open the Set Password Url.
3. Enter a password.

## Expected Behaviour

A new user with the correct mail address should have been created.

## Observed Behaviour

Error message: `Your activation token has expired, you will need to get another one sent to you.`

## Context

Registering a user to a mail adress with only lower case characters resulted in the expected behaviour. But when the mail address contains just one upper case character, the observed behaviour happened.

## Technical Info

* Browser Name and version: Firefox 81.0.2 (64-Bit)
* Operating System and version (desktop or mobile): Ubuntu 16.04.6 LTS

### `web.log`

```
{"name":"web","hostname":"c5aaab20f1e6","pid":114,"level":30,"key":"mongo.UserGetter.getUserByMainEmail","args":{},"elapsedTime":1,"msg":"[Metrics] timed async method call","time":"2020-10-20T16:06:38.469Z","v":0}
{"name":"web","hostname":"c5aaab20f1e6","pid":114,"level":40,"req":{"url":"/user/password/set","method":"POST","referrer":"https://server5.example.com:2025/user/activate?token=ab2c8a7585a1854a4c138417e21349a7597dbb02eb41017cc0e94ce686546415&user_id=5f8f0afdbc86ea00729c7c46","remote-addr":"172.29.248.148","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0","content-length":"156"},"res":{"statusCode":404},"response-time":8031,"msg":"POST /user/password/set","time":"2020-10-20T16:06:38.470Z","v":0}
```

**Comment by jdleesmiller** [comment]
This should be fixed in the latest release, as per https://github.com/overleaf/overleaf/issues/819#issuecomment-767429912 .
