### ISSUE TITLE
[BUG] :s/.../.../c broken (vim mode)

### ISSUE THREAD

**Issue by gustaphe** [overleaf/web#743]
## Steps to Reproduce

1. In vim-mode (in a file containing `pattern`), write `:s/pattern/subtsitution/gc` (followed by enter). 
2. Press one of the offered options (like `y`).

## Expected Behaviour

It should replace the found instance of `pattern` by `substitution`.

## Observed Behaviour

It finds an instance of `pattern`, a bar shows up saying "Replace with `substitution` (y/n/a/q/l)". However, I am in normal mode (so pressing `y`, for instance, only starts a yank). The bar doesn't disappear until I close or reload the tab.

## Context

Just trying to edit files.

## Technical Info

* URL: any overleaf.com/project/<number>
* Browser Name and version: Brave V1.16.76 (have also previously observed this bug in chromium)
* Operating System and version (desktop or mobile): Arch Linux / desktop
* Signed in as: 
* Project and/or file: any of the ones I've tried

**Comment by tyzoid** [comment]
This issue is also observed in firefox 86.0.1 on Arch Linux

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
