### ISSUE TITLE
Feature Request: Word Count History / Statistics over time

### ISSUE THREAD

**Issue by Nirostar** [overleaf/web#744]
I don't know if this is the right place for a feature request. Sorry if it isn't.

I would find it nice to have some kind of word count statistics over time. Maybe also for references, pages, characters, changes, etc. Especially for a long project, it can be very nice to see which progress you already made, and when you slacked or when you did well.

I hope this feature is also useful for others

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
