### ISSUE TITLE
french guillemets (« ») are not the same size in the text editor.

### ISSUE THREAD

**Issue by PyMarc2** [overleaf/web#745]
![image](https://user-images.githubusercontent.com/31829033/101283360-cccd3a00-37a7-11eb-8163-8cbb9699f9ef.png)

## Steps to reproduce
1. With French/English Canadian multistandard keyboard, type ALT+Z and ALT+X which will give « and ». 
2. Notice their size.

## Expected Behaviour
They should have the same size.

## Observed Behaviour
They don't.

## Who Needs to Know?
French people.

## Why is this important?
It is not, but it is extremely annoying!

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
