### ISSUE TITLE
How to get the newly added folder'id created by addFolder

### ISSUE THREAD

**Issue by Jeffrey9130** [overleaf/web#746]
As the title, when a new folder is created by ProjectEntityUpdateHandler.addFolder, how can I get the correct id of it?

**Comment by das7pad** [comment]
You can try this:
```js
// callback based
ProjectEntityUpdateHandler.addFolder(projectId, parentFolderId, folderName, (error, folder) => {
  console.log(folder._id)
})

// async/await
const { folder } = await ProjectEntityUpdateHandler.promises.addFolder(projectId, parentFolderId, folderName)
console.log(folder._id)
```

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
