### ISSUE TITLE
Feature request: Export PDF with comments

### ISSUE THREAD

**Issue by filipefigcorreia** [overleaf/web#747]
I suggest a feature to download the output PDF including the comments added through overleaf's UI. I believe that this could be achieved fairly easily, for example, by integrating with [pdfcomment.sty](https://ctan.org/tex-archive/macros/latex/contrib/pdfcomment). Here's [an example](https://mirrors.concertpass.com/tex-archive/macros/latex/contrib/pdfcomment/doc/example.pdf) of a PDF using pdfcomment.sty.

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
