### ISSUE TITLE
Feature request: Integration of Grammarly in rich text (just like 3rd party extension: https://github.com/robindijkhof/overleaf-textarea) 

### ISSUE THREAD

**Issue by shakeebmurtaza** [overleaf/web#749]
Please add Grammarly support by converting rich text as textbox or add another pane just like 3rd partly extension doing (https://github.com/robindijkhof/overleaf-textarea). If the team is unable to do this due to their busy schedule, then please integrate the 3rd party extension code in overleaf after reviewing (https://github.com/robindijkhof/overleaf-textarea).

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
