### ISSUE TITLE
Go to code location from PDF not working for specific subsection titles

### ISSUE THREAD

**Issue by LKreutzer** [overleaf/web#751]
I noticed that overleaf web would not jump to the current code location by double clicking the PDF for one chapter of a larger document. I removed parts of the chapter and found that it worked again when I removed the line ' \subsection{xxxxxx}' while leaving its content intact. If this line was present the PDF-to-code-location would not work when double clicking the PDF or when using the arrow navigation, for the entire chapter that the subsection was in. 

Even just changing the xxxxx in the concerned ' \subsection{xxxxxx}' made the feature work again after compiling the PDF anew. I.e. make it ' \subsection{xxxxxxABC}' and it works again after compiling. Changing it back to ' \subsection{xxxxxx}' and compiling again it stop working again. Only one specific subsection title, made up of latin characters caused this problem. 

Firefox Browser 85.0.1 64-bit
Ubuntu 18.04 LTS

Restarting the web browser and restarting the computer did not change anything.

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
