### ISSUE TITLE
Feature Request: History search function and git history

### ISSUE THREAD

**Issue by Tie-fighter** [overleaf/web#753]
I was looking for a piece of text that was missing, but I couldn't find it.
So I thought I had deleted it and wanted to search the history.

Unfortunately the history does not provide a search function.
I tried cloning using git instead but git does not provide a history.

Please consider implementing a search function (maybe not just for the history) and start track changes at project creation, not at first git clone.

Thank you!

(I found the missing text in the end manually.)

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
