### ISSUE TITLE
File tree now using numerical sort

### ISSUE THREAD

**Issue by paolieri** [overleaf/web#754]
## Steps to Reproduce

1. Create an empty project
2. Create empty files called `file_2ca.tex` `file_02d.tex` `file_2ea.tex`

## Expected Behaviour

The file names should be listed in alphabetical order, like `ls` or `ls -1 | sort` would show them:

```
file_02d.tex
file_2ca.tex
file_2ea.tex
```

## Observed Behaviour

The file names are listed in "numerical alphabetical order":

![image](https://user-images.githubusercontent.com/1083642/110219765-f44ea400-7e75-11eb-8fb8-4039ea014721.png)

This is the order that `ls -1 | sort -n` would use.

## Context

When files have hex values in their name (e.g., hashes or checksums), this ordering is not reliable because initial 0's in the hex string are ignored.

## Technical Info

The numerical file ordering is imposed by this source line in Overleaf:
[/frontend/js/features/file-tree/components/file-tree-folder-list.js#L69](https://github.com/overleaf/web/blob/59c7651d3709c86297e57439248a828318092281/frontend/js/features/file-tree/components/file-tree-folder-list.js#L69)

It appears that [this pull request](https://github.com/overleaf/web/commit/df7b59659cfa85635e66c1115d9f4ab6a4053bfd) introduced this change in December 2020.

The problem is reproducible on any browser and appears to be the new intended behavior.

## Analysis

There is nothing preventing the user from manually sorting these entries, for example by using this function:

``` js
function sortFileList(ul){
  var sorted = [];
  for (var i = ul.childNodes.length; i--;) {
    if (ul.childNodes[i].nodeName === 'LI')
      sorted.push(ul.childNodes[i]);
    }

    sorted.sort(function(a, b) {
      return b.getAttribute("aria-label") < a.getAttribute("aria-label");
    });

    var new_ul = ul.cloneNode(false);
    for(var i = 0; i < sorted.length; i++)
        new_ul.appendChild(sorted[i]);
    ul.parentNode.replaceChild(new_ul, ul);
}

sortFileList(document.getElementsByClassName('file-tree-list')[0]);
```
Afterward, the file list appears in the correct order:

![image](https://user-images.githubusercontent.com/1083642/110220517-00893000-7e7b-11eb-8750-c8cf9a2882bf.png)

It would be nice to give an option to the user, e.g., "Use numerical order in file tree".

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
