### ISSUE TITLE
Feature request: keyboard shortcut to view pdf

### ISSUE THREAD

**Issue by nathanielvirgo** [overleaf/web#756]
I'm unable to view the source and the pdf on screen simultaneously, because I use a large font size due to poor eyesight / small screen size. Consequently, in order to view what I've written, I have to click on the pdf icon, then (if needed) the recompile button, and then click back on the .tex file to go back into editing mode.

It would make an *enormous* difference if there were keyboard shortcuts for these actions - one to switch to the pdf and recompile, and another to go back to the .tex source. The process of editing and viewing my work would become much smoother. It would be incredibly helpful to have shortcuts for this, for people who like to work this way.

Alternatively, if such a feature exists already, it would be helpful for it to be documented, for example at https://www.overleaf.com/articles/overleaf-keyboard-shortcuts/qykqfvmxdnjf

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
