### ISSUE TITLE
Usability: key other than F1 for showing shortcuts

### ISSUE THREAD

**Issue by nathanielvirgo** [overleaf/web#757]
The keyboard shortcut sheet at https://www.overleaf.com/articles/overleaf-keyboard-shortcuts/qykqfvmxdnjf lists the `F1` key for the following action:

> Show list of shortcuts. If a shortcut isn’t available on your keyboard or input method, you might trigger it from this list instead.

Unfortunately, most Macs released since 2019 or so don't have an F1 key, because they have a touch bar instead. While the user can configure the touch bar to show the function keys, they might not have it set up that way, which makes the list of shortcuts impossible to access.

Given the role of this shortcut in triggering events that can't be triggered from a given input device, it would be helpful to add another shortcut for it, so that it can itself be accessed from all input devices.

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
