### ISSUE TITLE
[Feature Request] Custom environment/command templates for tab-completion

### ISSUE THREAD

**Issue by janniklasrose** [overleaf/web#758]
When I type `\begin{f` and select the `figure` environment to <kbd>Tab</kbd>-complete, I get

```latex
\begin{figure}
    \centering
    \includegraphics{}
    \caption{Caption}
    \label{fig:my_label}
\end{figure}
```

Depending on user preference or type of project, this is not always the most convenient or even correct default. Using the example of the `figure` environment, when using `memoir` the `\centerfloat` command centers figures even if they are wider than `\textwidth`. While it is of course possible to patch the `figure` environment in the preamble or custom class (to also accomplish other things like positioning with `[h]`), this is definitely something for the more advanced *LaTeX*er than using the Overleaf web interface.

Other use cases include:

- Enable automatic `\label` after `\chapter` or other section commands.
- Enable/disable automatic `\label` inside `table`/`figure`.
- Automatically pre-fill width for `\includegraphics[width=\textwidth]` command.
- Provide fancier `table` template, for example one that uses `tabularx`.

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
