### ISSUE TITLE
Redirect to Login Mask for Read Only Users

### ISSUE THREAD

**Issue by cmprmsd** [overleaf/web#760]
## Steps to Reproduce

1. Create a LaTeX document
2. Invite someone with "Read Only" permissions
3. Accept the invite and open the report as invited user

## Expected Behaviour

The page should now redirect you to the report and view it.

## Observed Behaviour

The user will see the loading Overleaf icon and then there is a redirect to the login mask, although the user is logged in.

## Context

Users cannot see the document I want them to be able to see.

## Technical Info

I'm using the dockerized version with nginx and websockets enabled.

**Comment by cmprmsd** [comment]
Hey,
I have not heard back yet. 
We're going to troubleshoot the issue this week at our work.

If you have any ideas, what's causing the redirect, feel free to share :)

**Comment by cmprmsd** [comment]
Following up the analysis of this problem. I still do not understand the reason for  this redirect.

When I open a page with read only permissions I can see the project in my shared projects.
Once I open it, the page loads and immediately redirects me to a login form:
![image](https://user-images.githubusercontent.com/73472903/114543442-81e19880-9c59-11eb-99d0-c06c0ffdab7a.png)

As you can see, I am still logged in, as the head navigation shows projects and account as well as my defails when I click on Account.

In BurpSuite the traffic looks like this:
![image](https://user-images.githubusercontent.com/73472903/114543905-2532ad80-9c5a-11eb-82a2-6f88ddd0bbab.png)
I load the page, there is no redirect, but my client requests the login page and displays it after seeing its first 403 forbidden.

This seems to be a permission issue with ReadOnly projects. I think this has to be fixed on the web server code as I sometimes manage to break the redirect request and have the page loaded correctly.

**Comment by cmprmsd** [comment]
Hi,

Can you please have a look here? I'd really like to close this issue with the cause fixed.

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
