### ISSUE TITLE
[Feature request] A way to locally rename a shared project that is owned by another user

### ISSUE THREAD

**Issue by przemyslslaw** [overleaf/web#761]
I have many projects in my Overleaf directory of All Projects, including many Shared documents that were created by my collaborators (so I don't own them). Currently, Overleaf doesn't allow me to rename projects that I don't own. Since I cannot name the documents myself, it makes it harder to keep track of all the projects. This issue could be solved by adding a layer of user-specific project names on top of the owner-specific project names, so that the default name is the one given by the owner, but each user can give the project its own name.

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
