### ISSUE TITLE
[Feature request] Per-user/per-session main document

### ISSUE THREAD

**Issue by rinkp** [overleaf/web#762]
The current feature set includes the ability to set a main document for a project. This document is used if you do not have a `.tex` file open that is a full document.

Sometimes you want to collaborate with multiple users in the same project, but do not want to compile the same document. For these cases it would be nice to be able to set a main document per session or per user. 

_No feature request has been created before for this_

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
