### ISSUE TITLE
[Feature request] Nested Folders

### ISSUE THREAD

**Issue by M-Colley** [overleaf/web#763]
Hello, 

I often find myself needing folders to, for example, group projects for a conference. These occur per year. Today, I have a folder for every year on the top-layer. However, I think nested folders would be very helpful here.

Kind regards

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
