### ISSUE TITLE
feature request: preview *values* in dropdown of ref commands

### ISSUE THREAD

**Issue by jeisner** [overleaf/web#764]
Here's a feature that would be awesome!

When I type `\cref{sec:` I get a dropdown list of section labels.
When I type `\cref{thm:` I get a drop-down list of theorem labels.  
That's quite helpful.
Alas, my coauthor uses labels whose meaning is hard for me to interpret.  
So it would be far more helpful if the dropdown list **also showed the text that would be rendered by the `\cref` command**, e.g.,
```
\cref{thm:blowup}                   Theorem 2
\cref{thm:closure}                    Lemma 5
\cref{thm:eccp-to-marginalized}   Theorem A.1
...
```
After all, I can see in the PDF that the thing I want to refer to is `Lemma 5`, and that's how _I_ think of it at the moment, and it's a real distraction from writing to have to go navigate into some other .tex file to look up whatever silly tag :-P my coauthor picked for it.

Same thing for other reference commands like `\ref`, `\pageref`, and `\autoref`, of course.  
And perhaps the citation commands, too.

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
