### ISSUE TITLE
Issue with the fileTreeManager findSelectedEntity function since 2.6.1

### ISSUE THREAD

**Issue by cmprmsd** [overleaf/web#765]
## Steps to Reproduce

1. Open a project and open a tex file
2. In your JS console run: `_ide.fileTreeManager.findSelectedEntity()` 
3. The entity is `null`

## Expected Behaviour
The query should return the current file, its id and name.
![image](https://user-images.githubusercontent.com/73472903/116704378-9baa0c00-a9cb-11eb-9c26-cc2594bccd87.png)

## Observed Behaviour
The entity is `null`

## Context
I created a plugin to paste images to the web application from the clipboard.
https://github.com/cmprmsd/Overleaf-Image-Helper
Therefore I need the name of the currently edited file from within the JavaScript client context.

@mserranom Could you point me in the right direction? I'm sure there are other ways to read the current file name.

Edit: I found another route. However, it's getting more complicated.
```javascript
_ide.fileTreeManager.findEntityById(_ide.$scope.editor.open_doc_id).name
```
Maybe it's worth fixing the findSelectedEntity() function.

**Comment by mserranom** [comment]
Cc @timothee-alby

**Comment by timothee-alby** [comment]
Hello,

We're in the process of migrating our front-end to React and will be gradually removing/breaking the Angular code. Sorry about that. 

As an alternative you may want to get the DOM node of the selected file with `document.querySelector('.file-tree-list li.selected')` or the file `id` with `_ide.editorManager.$scope.editor.sharejs_doc.doc.doc_id`. However this may break in the near future as we transition more of our codebase to React.


Handy plugging by the way! I'll cast a vote for this feature in our internal ideas list.
