### ISSUE TITLE
Wordcount includes words in comment-environment

### ISSUE THREAD

**Issue by M-Colley** [overleaf/web#767]
Hello, when omitting certain text via the \begin{comment} environment, the words are still counted via the menu -> wordcount option. I would expect that these words would **_not_** be counted.

Kind regards

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
