### ISSUE TITLE
backup of overleaf papers is broken

### ISSUE THREAD

**Issue by monperrus** [overleaf/web#770]
Thanks a lot for overleaf, which is essential to our scientific life.

I have a backup script of all my overleaf papers. It is based on the endpoint `https://www.overleaf.com/user/projects`.

The  backup script is broken due to  `{"errorReason":"cannot_verify_user_not_robot","message":{"text":"Sorry, we could not verify that you are not a robot. Please check that Google reCAPTCHA is not being blocked by an ad blocker or firewall."}}`

How to again do an automated backup of all my overleaf papers?

## Steps to Reproduce

1. Connect programmatically to overleaf
2. Call `https://www.overleaf.com/user/projects`

## Expected Behaviour

Receiving the list of papers

## Observed Behaviour

Error with `{"errorReason":"cannot_verify_user_not_robot","message":{"text":"Sorry, we could not verify that you are not a robot. Please check that Google reCAPTCHA is not being blocked by an ad blocker or firewall."}}`

**Comment by jdleesmiller** [comment]
Thanks for reporting this.

We have had to introduce reCAPTCHA on the login page in response to recent abuse. This has unfortunately broken any scripts that people may have written to list their projects.

Technically, we do not support use of any such scripts, but I think what might work would be: log in interactively in your browser, capture your session cookie, and put the session cookie in the script's cookie jar. If the script runs regularly, it will keep touching the session, which should keep it valid. (It will also then appear on your [sessions page](https://www.overleaf.com/user/sessions).)

Longer term, I hope that we will have an API that will make it possible to do this in an officially supported way!

**Comment by monperrus** [comment]
Hi John,

Thanks for the workaround.

Looking forward to the official API, it would be so useful!

--Martin
