### ISSUE TITLE
[Feature Request] Show Beamer Frames as Sections in Outline

### ISSUE THREAD

**Issue by Faibk** [overleaf/web#771]
I love the new file outline! Especially for large files it allows fast navigation and I sometimes use it to pre-structure my papers.

I also prepare my presentation slides on Overleaf using Beamer. It would be very nice if the frames would appear as subsections in the file outline, so I can see how my presentation is structured.

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
