### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by zidingz** [overleaf/web#774]
Hi there,

I couldn't find a `SECURITY.md` in your repository and am not sure how to best contact you privately to disclose a security issue.

Can you add a `SECURITY.md` file with an e-mail to your repository, so that our system can send you the vulnerability details? GitHub suggests that a [security policy](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) is the best way to make sure security issues are responsibly disclosed.

Once you've done that, you should receive an e-mail within the next hour with more info.

Thanks! (cc @huntr-helper)

**Comment by jdleesmiller** [comment]
Hi there, we'll look at adding a SECURITY.md, but in the interim you can find this information in the [`CONTRIBUTING.md`](https://github.com/overleaf/overleaf/blob/245fc120e6d50e8ee02d5900b8d6a8d6d8b9135c/CONTRIBUTING.md#security) in our root repo.

**Comment by zidingz** [comment]
Thank you very much! Emails will be with you within the hour.

Here's a tiny security policy draft if it'll save you time: https://github.com/overleaf/web/pull/775

**Comment by das7pad** [comment]
This has been dealt with internally. Thanks again for getting in contact with us.
